export interface Order {
  order_id: string;
  sum: string;
  is_paid: boolean;
  paid: string;
  date: string;
  shipping_cost: string;
  shipping_id: string;
}

// {
//     "order_id": "4",
//     "user_id": "8",
//     "date": "2021-05-17 23:37:31",
//     "status_date": "2021-05-17 23:37:31",
//     "confirm_date": "0000-00-00 00:00:00",
//     "delivery_date": "0000-00-00",
//     "status_id": "1",
//     "sum": "69.20",
//     "payment_id": "12",
//     "user_order": "0",
//     "shipping_id": "13",
//     "shipping_cost": "0.00",
//     "email": "ugicjkwxnl+533738838@allegromail.pl",
//     "delivery_code": "",
//     "code": "ffb691b656ab9b2f3d16484574d72dce",
//     "confirm": "0",
//     "notes": "Punkt odbioru:\nAdres: Brody 8A\nKod pocztowy: 43-450\nMiasto: Ustroń\nNazwa punktu odbioru: Paczkomat UST01A\nDodatkowe informacje: Przy pawilonie handlowym, obok apteki Dr LIBRO",
//     "notes_priv": "",
//     "notes_pub": "",
//     "currency_id": "1",
//     "currency_rate": "1",
//     "paid": "69.20",
//     "ip_address": "",
//     "discount_client": "0",
//     "discount_group": "0",
//     "discount_levels": "0",
//     "discount_code": "0",
//     "code_id": null,
//     "lang_id": "1",
//     "origin": "3",
//     "parent_order_id": null,
//     "registered": "0",
//     "auction": {
//         "auction_order_id": "1",
//         "auction_id": null,
//         "real_auction_id": "10480774425",
//         "order_id": "4",
//         "auction_house_id": "1",
//         "buyer_id": "1077808",
//         "payment_time": "2021-05-17 23:37:39",
//         "payment_method": "Przelewy24",
//         "shipment_method": "Allegro Paczkomaty InPost",
//         "transaction_id": "f8a40a72-b757-11eb-8650-d3f0220ebe06",
//         "buyer_login": "mac83",
//         "deal_id": "f31ca2b0-b757-11eb-811c-23eab94d12d4"
//     },
//     "promo_code": "",
//     "additional_fields": [],
//     "pickup_point": "UST01A",
//     "shipping_additional_fields": {
//         "machine": "UST01A",
//         "shipment_id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93"
//     },
//     "tags": [],
//     "is_paid": true,
//     "is_overpayment": false,
//     "is_underpayment": false,
//     "total_parcels": 0,
//     "total_products": 1,
//     "children": [],
//     "loyalty_cost": 0,
//     "loyalty_score": 0,
//     "vat_eu": false,
//     "shipping_tax_name": "23%",
//     "shipping_tax_value": "23",
//     "shipping_tax_id": "1",
//     "delivery_address": {
//         "address_id": "5",
//         "order_id": "4",
//         "type": "2",
//         "firstname": "Ewa",
//         "lastname": "Byrtek",
//         "company": "",
//         "pesel": "",
//         "city": "Ustroń",
//         "postcode": "43-450",
//         "street1": "ul. Błaszczyka 3A",
//         "street2": "",
//         "state": "",
//         "country": "Polska",
//         "phone": "0048694112882",
//         "country_code": "PL",
//         "tax_identification_number": ""
//     },
//     "billing_address": {
//         "address_id": "4",
//         "order_id": "4",
//         "type": "1",
//         "firstname": "Mariusz",
//         "lastname": "Byrtek",
//         "company": "",
//         "pesel": "",
//         "city": "Ustroń",
//         "postcode": "43-450",
//         "street1": "ul. Błaszczyka 3A",
//         "street2": "",
//         "state": "",
//         "country": "Polska",
//         "phone": "0048504016263",
//         "country_code": "PL",
//         "tax_identification_number": ""
//     }
// }
